language: go

go:
  - 1.2

script: ./bin/test -skip="wshd Suite" -skipMeasurements -skip=Lifecycle

env:
  global:
    - secure: PBR1JWF0XnZG8vHGGKVAHZ++Pgso9k2AYdPGAKF9qN1cv4Kc/b09R2yEIMgvZdPL25fmAkb6O2R6NNwmNUBwpuNGpI2fVEOFgsPWaYuj2Kk31DMqMDC9arWbyFE2+2cocj5r5fF+QDsKgQa7VHJ1Gge5145f3qjPlg2JUgmjXpQ=
