language: go
go:
  - 1.1.2
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - gem install eventmachine -v 0.12.10
  - gem install thin -v 1.4.1
  - gem install nats -v 0.4.28
  - go get -v ./...
  - go get -v github.com/onsi/ginkgo
  - go install -v github.com/onsi/ginkgo/ginkgo
  - pushd ../../coreos/etcd
  - ./build
  - mv ./etcd $HOME/gopath/bin
  - popd
  - mkdir -p $HOME/bin
  - pushd $HOME/bin
  - curl -C - http://apache.osuosl.org/zookeeper/zookeeper-3.4.5/zookeeper-3.4.5.tar.gz | tar -zx
  - mv $HOME/bin/zookeeper-3.4.5 $HOME/bin/zookeeper
  - chmod a+x $HOME/bin/zookeeper/bin/zkServer.sh
  - popd

script:
  - export PATH=$HOME/bin/zookeeper/bin:$HOME/gopath/bin:$PATH
  - ginkgo -r -i --randomizeAllSpecs --failOnPending --skipMeasurements